apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - targetPort: 3306
    interval: 30s