apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-slave
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server-slave.default.svc.cluster.local
    path: "/"